debug = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]
  entryPoint = "traefik"
  dashboard = true

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "romanpeters.nl"
  watch = true

[traefikLog]
filePath = "/var/log/traefik/traefik.log"

[accessLog]
filePath = "/var/log/traefik/access.log"

[file]
[frontends]
  [frontends.frontend-landingpage-romanpeters-nl]
  backend = "backend-landingpage"
    [frontends.frontend-landingpage-romanpeters-nl.routes.test_1]
    rule = "Host: landingpage.romanpeters.nl"

  [frontends.frontend-home-romanpeters-nl]
  backend = "backend-home-assistant"
    [frontends.frontend-home-romanpeters-nl.routes.test_1]
    rule = "Host: home.romanpeters.nl"

  [frontends.frontend-plex-romanpeters-nl]
  backend = "backend-plex"
    [frontends.frontend-plex-romanpeters-nl.routes.test_1]
    rule = "Host: plex.romanpeters.nl"

  [frontends.frontend-synology-romanpeters-nl]
  backend = "backend-synology"
    [frontends.frontend-synology-romanpeters-nl.routes.test_1]
    rule = "Host: synology.romanpeters.nl"

  [frontends.frontend-homebridge-romanpeters-nl]
  backend = "backend-homebridge"
    [frontends.frontend-homebridge-romanpeters-nl.routes.test_1]
    rule = "Host: homebridge.romanpeters.nl"

  [frontends.frontend-pi-hole-romanpeters-nl]
  backend = "backend-pi-hole"
    [frontends.frontend-pi-hole-romanpeters-nl.routes.test_1]
    rule = "Host: pi-hole.romanpeters.nl"

[backends]
  [backends.backend-landingpage]
    [backends.backend-landingpage.servers.server1]
    url = "http://10.10.10.20:5001"

  [backends.backend-home-assistant]
    [backends.backend-home-assistant.servers.server1]
    url = "http://10.10.10.20:8123"

  [backends.backend-plex]
    [backends.backend-plex.servers.server1]
    url = "http://10.10.10.20:32400"

  [backends.backend-synology]
    [backends.backend-synology.servers.server1]
    url = "http://10.10.10.100:3998"

  [backends.backend-homebridge]
    [backends.backend-homebridge.servers.server1]
    url = "http://10.10.10.20:8780"

  [backends.backend-pi-hole]
    [backends.backend-pi-hole.servers.server1]
    url = "http://10.10.10.101"

[acme]
email = "traefik@romanpeters.nl"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "transip"
  

[[acme.domains]]
  main = "*.romanpeters.nl"

[[acme.domains]]
  main = "e-surveillant.nl"
  sans = ["www.e-surveillant.nl"]

[[acme.domains]]
  main = "*.devops-utrecht.nl"
