debug = false
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[web]  #Run Traefik info page at 8080. 
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/server.cert"
      keyFile = "/certs/server.pem"

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "server.local"
  watch = true


# API definition
[api]
  entryPoint = "traefik"
  dashboard = true

[file]
[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host: server.local"

  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
    rule = "Host: home.server.local"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://10.10.10.20:1080"

  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://10.10.10.20:8123"

#[frontends]
#  [frontends.landingpage]
#  backend = "backend-landingpage"
#    [frontends.landingpage.routes.route1]
#    rule = "Host:server.local"

#  [frontends.homeassistant]
#    backend="homeassistant"
#    entryPoints = ["http", "https"]
#    passHostHeader = true
##    proirity = 20
#    [frontends.homeassistant.routes.route1]
#      rule="Host:home.server.local"

#[backends]
#  [backends.landingpage]
#    [backends.landingpage.servers.host1]
#    url = "http://10.10.10.20:1080"

#  [backends.homeassistant]
#    [backends.homeassistant.servers.host1]
#    url = "http://10.10.10.20:8123"
##    weight = 10
