debug = false
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[web]  #Run Traefik info page at 8080. 
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/server.cert"
      keyFile = "/certs/server.pem"

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "server.local"
  watch = true


# API definition
[api]
  entryPoint = "traefik"
  dashboard = true

[file]
[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host: landingpage.romanpeters.nl"

  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
    rule = "Host: home.romanpeters.nl"

#  [frontends.frontend3]
#  backend = "backend3"
#    [frontends.frontend3.routes.test_1]
#    rule = "Host: plex.romanpeters.nl"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://10.10.10.20:1080"

  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://10.10.10.20:8123"

#  [backends.backend3]
#    [backends.backend3.servers.server1]
#    url = "http://10.10.10.20:32400"
