debug = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]
  entryPoint = "traefik"
  dashboard = true

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "romanpeters.nl"
  watch = true
  passHostHeader = true


[traefikLog]
filePath = "/var/log/traefik/traefik.log"

[accessLog]
filePath = "/var/log/traefik/access.log"

[file]
[frontends]
  [frontends.frontend-synology-romanpeters-nl]
  backend = "backend-synology"
    [frontends.frontend-synology-romanpeters-nl.routes.test_1]
    rule = "Host: synology.romanpeters.nl"

  [frontends.frontend-nextcloud-romanpeters-nl]
  backend = "backend-nextcloud"
  passHostHeader = true
    [frontends.frontend-nextcloud-romanpeters-nl.routes.test_1]
    rule = "Host: files.romanpeters.nl"

  [frontends.frontend-pi-hole-romanpeters-nl]
  backend = "backend-pi-hole"
    [frontends.frontend-pi-hole-romanpeters-nl.routes.test_1]
    rule = "Host: pi-hole.romanpeters.nl"

  [frontends.frontend-vault-romanpeters-nl]
  backend = "backend-vault"
    [frontends.frontend-vault-romanpeters-nl.routes.test_1]
    rule = "Host: vault.romanpeters.nl"

  [frontends.frontend-plex-romanpeters-nl]
  backend = "backend-plex"
    [frontends.frontend-plex-romanpeters-nl.routes.test_1]
    rule = "Host: plex.romanpeters.nl"

  [frontends.frontend-home-romanpeters-nl]
  backend = "backend-home"
    [frontends.frontend-home-romanpeters-nl.routes.test_1]
    rule = "Host: home.romanpeters.nl"

[backends]
  [backends.backend-synology]
    [backends.backend-synology.servers.server1]
    url = "http://10.10.10.100:3998"

  [backends.backend-nextcloud]
    [backends.backend-nextcloud.servers.server1]
    url = "http://10.10.10.20:1452"

  [backends.backend-pi-hole]
    [backends.backend-pi-hole.servers.server1]
    url = "http://10.10.10.101"

  [backends.backend-vault]
    [backends.backend-vault.servers.server1]
    url = "http://10.10.10.20:8200/ui"

  [backends.backend-plex]
    [backends.backend-plex.servers.server1]
    url = "http://10.10.10.20:32400"

  [backends.backend-home]
    [backends.backend-home.servers.server1]
    url = "http://10.10.10.20:8123"

[acme]
email = "traefik@romanpeters.nl"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
#  [acme.httpChallenge]
#  entryPoint = "http"

[[acme.domains]]
  main = "*.romanpeters.nl"
  sans = ["romanpeters.nl"]
#  main = "romanpeters.nl"
#  sans = ["files.romanpeters.nl", "home.romanpeters.nl", "glances.romanpeters.nl", "sharelatex.romanpeters.nl", "radarr.romanpeters.nl", "sonarr.romanpeters.nl", "start.romanpeters.nl"]

[[acme.domains]]
  main = "e-surveillant.nl"
  sans = ["www.e-surveillant.nl"]

[[acme.domains]]
#  main = "*.devops-utrecht.nl"
  main = "devops-utrecht.nl"
