debug = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]
  entryPoint = "traefik"
  dashboard = true

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "romanpeters.nl"
  watch = true
  passHostHeader = true


[traefikLog]
filePath = "/var/log/traefik/traefik.log"

[accessLog]
filePath = "/var/log/traefik/access.log"

[file]
[frontends]
  [frontends.frontend-synology-romanpeters-nl]
  backend = "backend-synology"
    [frontends.frontend-synology-romanpeters-nl.routes.test_1]
    rule = "Host: synology.romanpeters.nl"

  [frontends.frontend-nextcloud-romanpeters-nl]
  backend = "backend-nextcloud"
  passHostHeader = true
    [frontends.frontend-nextcloud-romanpeters-nl.routes.test_1]
    rule = "Host: files.romanpeters.nl"

  [frontends.frontend-pi-hole-romanpeters-nl]
  backend = "backend-pi-hole"
    [frontends.frontend-pi-hole-romanpeters-nl.routes.test_1]
    rule = "Host: pi-hole.romanpeters.nl"

[backends]
  [backends.backend-synology]
    [backends.backend-synology.servers.server1]
    url = "http://10.10.10.100:3998"

  [backends.backend-nextcloud]
    [backends.backend-nextcloud.servers.server1]
    url = "http://10.10.10.20:1452"

  [backends.backend-pi-hole]
    [backends.backend-pi-hole.servers.server1]
    url = "http://10.10.10.101"

[acme]
email = "traefik@romanpeters.nl"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
#  [acme.dnsChallenge]
#  provider = "transip"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
#  main = "*.romanpeters.nl"
  main = "romanpeters.nl"
  sans = ["files.romanpeters.nl", "plex.romanpeters.nl", "home.romanpeters.nl"]

[[acme.domains]]
  main = "e-surveillant.nl"
  sans = ["www.e-surveillant.nl"]

[[acme.domains]]
#  main = "*.devops-utrecht.nl"
  main = "devops-utrecht.nl"
