---
- hosts: "all"
  remote_user: "{{ user }}"
  become: true
  become_user: "root"
  become_method: "sudo"
  gather_facts: yes

  handlers:
    - import_tasks: "handlers/main.yml"

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python

  tasks:
    - name: "system"
      include_tasks: "tasks/system.yml"

    - name: "packages"
      include_tasks: "tasks/packages.yml"

    - name: "user"
      include_tasks: "tasks/user.yml"

    - name: "sshd"
      include_tasks: "tasks/ssh.yml"

    - name: "python"
      include_tasks: "tasks/python.yml"

    - name: "docker"
      include_tasks: "tasks/docker.yml"

    - name: "git"
      include_tasks: "tasks/git.yml"

    - name: "zsh"
      include_tasks: "tasks/zsh.yml"

- hosts: "nuc"
  remote_user: "{{ user }}"
  become: true
  become_user: "root"
  become_method: "sudo"
  gather_facts: yes

  tasks:
    - name: "traefik"
      include_tasks: "tasks/traefik.yml"

    - name: "synology"
      include_tasks: "tasks/synology.yml"

    - name: "nextcloud"
      include_tasks: "tasks/nextcloud.yml"

    - name: "e-surveillant"
      include_tasks: "tasks/e-surveillant.yml"

    - name: "devops"
      include_tasks: "tasks/devops.yml"

    - name: "portainer"
      include_tasks: "tasks/portainer.yml"

    - name: "minecraft"
      include_tasks: "tasks/minecraft.yml"

    - name: "home stack"
      include_tasks: "tasks/home_stack.yml"

    - name: "plex stack"
      include_tasks: "tasks/plex_stack.yml"



