---
- name: "install git"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "git"

- name: "set git email"
  command: "git config --global user.email '{{ mail }}'"

- name: "set git name"
  command: "git config --global user.name '{{ full_name }}'"

- name: "read SSH public key to authorize"
  shell: "cat /home/{{ user }}/.ssh/id_rsa.pub"
  register: ssh_pub_key

- name: 'authorize key with GitHub'
  github_key:
    name: "{{ hostname }}"
    token: "{{ github_token }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
