---
- name: "create Glances container"
  docker_container:
    name: glances
    image: nicolargo/glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "61208:61208"
      - "61209:61209"
    env:
      GLANCES_OPT: "-w"
    pid_mode: host
    networks:
      - name: traefik_proxy
    restart_policy: always
    restart: yes
    labels:
      traefik.port: "61208"
      traefik.backend: glances
      traefik.frontend.rule: "Host:glances.romanpeters.nl"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: "example.com"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"

