---
- name: "create Grafana container"
  docker_container:
    name: grafana
    image: grafana/grafana
    restart_policy: always
    restart: yes
    networks:
      - name: traefik_proxy
#      - name: influx_net
    volumes:
      - /var/docker/grafana:/var/lib/grafana
    labels:
      traefik.port: "3000"
      traefik.frontend.rule: "Host:grafana.romanpeters.nl"
