---
- name: "create Heimdall container"
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    volumes:
      - /var/docker/heimdall:/config
    env:
      TZ: Europe/Amsterdam
      FORCE_HTTPS: "true"
    networks:
      - name: traefik_proxy
    restart_policy: always
    restart: yes
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:heimdall.romanpeters.nl,start.romanpeters.nl"
      traefik.frontend.auth.basic.users: "romanpeters:$apr1$iMEzu6Tq$7C655jttFu6PbtSR7jQJU/,tanlambrechtsen:$apr1$Ej1QoBY6$Q9wyRxVinbs9V7WvRrOBN."

