---
- name: create homeassistant directory
  file:
      path: /opt/homeassistant
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

- name: pull Homeassistant Config
  command: "rsync -avz {{ remote_backup_location }}hourly.0/localhost{{ item }} {{ item }}"
  with_items:
    - /opt/homeassistant/config/
  become: "{{ user }}"

- name: "create Home Assistant container"
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    privileged: yes

    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock:ro
    ports:
      - "8123:8123"
    network_mode: host
    restart_policy: always
    restart: yes
    state: started
    labels:
      traefik.enable: "false"

