---
#- name: "create Minecraft Server container"
#  docker_container:
#    name: minecraft-server
#    image: itzg/minecraft-server
#    state: started
#    env:
#      EULA: "TRUE"
#      MEMORY: "10G"
#      VERSION: "SNAPSHOT"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: "testing"
#      RCON_PORT: "28016"
#      SEED: "-21937183521"
#      WHITELIST: "ElectricMonkey,Don_Deco"
##      TYPE: "PAPER"
#    ports:
#      - "1337:25565"
#    volumes:
#      - /opt/minecraft:/data
#    command: nogui
#    restart_policy: always
#    restart: yes
#    labels:
#      traefik.enable: "false"

- name: copy hibernate script
  copy:
      src: "templates{{ item }}"
      dest: "{{ item }}"
      remote_src: no
  with_items:
    - /opt/minecraft/hibernate.py

- name: copy hibernate service
  copy:
      src: "templates{{ item }}"
      dest: "{{ item }}"
      remote_src: no
  with_items:
    - /lib/systemd/system/mc-hibernate.service

- name: start and enable hibernate service
  service:
      name: mc-hibernate.service
      state: restarted
      enabled: yes



#- name: "create Minecraft Paper Server container"
#  docker_container:
#    name: minecraft-paper-server
#    image: itzg/minecraft-server
#    state: stopped
#    env:
#      EULA: "TRUE"
#      MEMORY: "10G"
##      VERSION: "SNAPSHOT"
#      ENABLE_RCON: "true"
#      SEED: "-21937183521"
#      WHITELIST: "ElectricMonkey,Don_Deco"
#      TYPE: "PAPER"
#    ports:
#      - "1337:25565"
#    volumes:
#      - /opt/minecraft-paper:/data
#    command: --noconsole
#    restart_policy: always
#    restart: yes
#    labels:
#      traefik.enable: "false"


- name: allow access to port 1337
  ufw:
    comment: Minecraft
    rule: allow
    port: 1337
