---
- name: "create nextcloud directories"
  file:
    path: "/usr/src/docker/nextcloud"
    state: directory

- name: "copy nextcloud docker-compose"
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
  with_items:
    - "/usr/src/docker/nextcloud/docker-compose.yml"

- name: "compose up nextcloud"
  docker_service:
    project_src: "/usr/src/docker/nextcloud"
