---
# Needed because of Ansible issue #25414
- name: "check if unattended-upgrades is not in progress"
  shell: "while fuser /var/lib/dpkg/lock; do sleep 1; done;"
  become: true
  changed_when: false

- name: "upgrade packages"
  apt:
    upgrade: "yes"
    update_cache: true

- name: "install common utilities"
  apt:
    name:
      - "aptitude"
      - "htop"
      - "tmux"
      - "grc"
      - "haveged"
      - "tree"
      - "bluez"
#      - "inotify-tools"
#      - "bluetooth"
      - "trash-cli"
      - "unzip"
      - "lolcat"
        #      - "software-properties-common"
        #      - "sl"
    state: "present"

    #    apt:
    #    name:
    #      - apt-transport-https
    #      - ca-certificates


