---
- name: "create Plex container"
  docker_container:
    name: plex
    image: linuxserver/plex
#    network_mode: host
    env:
      PUID: '1001'
      PGID: '1001'
      VERSION: docker
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plex/config:/config"
      - "/tmp/plex_transcode:/transcode"
      - "/home/{{ user }}/tvseries:/data/tvshows"
      - "/home/{{ user }}/movies:/data/movies"
#    ports:
#      - '32469:32469'
#      - '32469:32469/udp'
#      - '5353:5353/udp'
#      - '1900:1900/udp'
    restart_policy: always
    networks:
      - name: traefik_proxy
    restart: yes
    labels:
      traefik.port: "32400"
      traefik.frontend.rule: "Host:plex.server.local"    
      traefik.protocol: http
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: plex.server.local
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"


