---
- name: "create Plex container"
  docker_container:
    name: plex
    image: linuxserver/plex
    network_mode: host
    env:
      PUID: '1080'
      PGID: '1080'
      VERSION: docker
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plex/config:/config"
      - "/tmp/plex_transcode:/transcode"
      - "/home/{{ user }}/tvseries:/data/tvshows"
      - "/home/{{ user }}/movies:/data/movies"
      - "/home/{{ user_2 }}/movies:/data/{{ user_2 }}_movies"
      - "/home/{{ user_2 }}/tvseries:/data/{{ user_2 }}_tvshows"
    restart_policy: always
    restart: yes
    labels:
      traefik.enable: "false"

- name: allow access to port 32400
  ufw:
    comment: Plex
    rule: allow
    port: 32400
    src: "{{ item }}"
  with_items:
    - 10.10.10.0/24
    - 172.17.0.0/24
