---
- name: "create Portainer container"
  docker_container:
    name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    restart_policy: always
    restart: yes
    labels:
      traefik.port: "9000"
      traefik.frontend.rule: "Host:portainer.server.local"

