---
- name: "install Python utilities"
  apt:
    name:
      - "python-pip"

- name: "install Python essentials"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "python3-pip"
    - "virtualenv"
    - "build-essential"
    - "python3-dev"
