---
- name: Create docker-compose plex stack dir
  file:
    path: /var/docker-compose/sharelatex
    state: directory

- name: Copy sharelatex docker-compose
  template:
    src: templates/var/docker-compose/sharelatex/docker-compose.yml
    dest: /var/docker-compose/sharelatex/docker-compose.yml

- name: Compose up sharelatex
  docker_service:
    project_src: /var/docker-compose/sharelatex
