---
- name: "remove help text from motd"
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: "absent"
  with_items:
    - "10-help-text"

      #- name: "set time zone"
      #  command: "cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime"
