---
- name: "create Traefik directory"
  file:
    path: /var/docker/traefik/
    state: directory
    mode: 0755    

- name: "create acme.json"
  file:
    path: /var/docker/traefik/acme.json
    state: touch
    mode: 0600


- name: "copy Traefik configuration"
  template:
    src: "templates{{ item }}"
    dest: "{{ item }}"
  with_items:
    - "/var/docker/traefik/traefik.toml"


- name: "create Docker network"
  docker_network:
    name: traefik_proxy
    ipam_options:
      subnet: '172.1.1.1/16'

- name: "create Traefik container"
  docker_container:
    name: traefik
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    env:
      TRANSIP_ACCOUNT_NAME: "{{ user }}"
      TRANSIP_PRIVATE_KEY_PATH: "/certs/transip"
    networks:
      - name: traefik_proxy
        ipv4_address: 172.1.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/traefik/traefik.toml:/traefik.toml
      - /var/docker/traefik/certs/:/certs/
      - /var/docker/traefik/acme.json:/acme.json
      - /var/docker/traefik/logs:/var/log/traefik/
    labels:
      traefik.port: "8080"
      traefik.frontend.rule: "Host:traefik.romanpeters.nl"
    restart_policy: always
    restart: yes

