---
- name: "create mediamanager group"
  group:
    name: mediamanager
    gid: 1080
    system: yes

- name: "make sure user exists, has SSH keys and is in the root group"
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    state: present
    append: yes
    groups:
      - root
      - audio
      - mediamanager

- name: "create mediamanager user"
  user:
    name: mediamanager
    groups:
      - mediamanager
      - www-data
    append: 'yes'
    uid: 1080
    shell: /usr/sbin/nologin
    system: yes
    create_home: no
