---
- name: Set vars version
  set_fact:
    vault_v: 1.1.2

- name: Download vault
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_v}}/vault_{{vault_v}}_linux_amd64.zip
    dest: /tmp/vault_{{ vault_v }}.zip

- name: Unzip vault
  unarchive:
    src: /tmp/vault_{{ vault_v }}.zip
    dest: /usr/bin
    remote_src: yes

- name: Ensure vault dir exists
  file:
    path: /etc/vault/
    state: directory

- name: copy vault config
  copy:
      src: templates/etc/vault/config.hcl.j2
      dest: /etc/vault/config.hcl
      remote_src: no

- name: Copy vault service
  copy:
      src: templates/lib/systemd/system/vault.service
      dest: /lib/systemd/system/vault.service
      remote_src: no

- name: Start and enable vault service
  service:
      name: vault.service
      state: restarted
      enabled: yes



